export const KLplayers = [
    {
       "teamId":0,       
       "players":[
          {
             "id":0,
             "name":"Ricardo",
             "position":"POR",
             "image":"1k-ricardo.png"
          },
          {
             "id":1,
             "name":"Román",
             "position":"DF",
             "image":"1k-romn.png"
          },
          {
             "id":2,
             "name":"Sorroche",
             "position":"DC",
             "image":"1k-sorroche.png"
          },
          {
             "id":3,
             "name":"Marino",
             "position":"DC",
             "image":"1k-marino.png"
          },
          {
             "id":4,
             "name":"Ledo",
             "position":"DF",
             "image":"1k-ledo.png"
          },
          {
             "id":5,
             "name":"Sauras",
             "position":"DF",
             "image":"1k-sauras.png"
          },
          {
             "id":6,
             "name":"Bruno",
             "position":"DF",
             "image":"1k-bruno.png"
          },
          {
             "id":7,
             "name":"Pluvins",
             "position":"MC",
             "image":"1k-pluvins.png"
          },
          {
             "id":8,
             "name":"Rivero",
             "position":"MC",
             "image":"1k-rivero.png"
          },
          {
             "id":9,
             "name":"Lautaro",
             "position":"DC",
             "image":"1k-lautaro.png"
          },
          {
             "id":10,
             "name":"Günter",
             "position":"DC",
             "image":"1k-gnter.png"
          }
       ]
    },
    {
       "teamId":1,       
       "players":[
          {
             "id":0,
             "name":"José Juan",
             "position":"POR",
             "image":"el-barrio-jos-juan.png"
          },
          {
             "id":1,
             "name":"Jacobo",
             "position":"DC",
             "image":"el-barrio-jacobo.png"
          },
          {
             "id":2,
             "name":"Mase",
             "position":"DF",
             "image":"el-barrio-mase.png"
          },
          {
             "id":3,
             "name":"Beguer",
             "position":"DC",
             "image":"el-barrio-beguer.png"
          },
          {
             "id":4,
             "name":"Ros",
             "position":"MC",
             "image":"el-barrio-ros.png"
          },
          {
             "id":5,
             "name":"Ubón",
             "position":"MC",
             "image":"el-barrio-ubn.png"
          },
          {
             "id":6,
             "name":"Pau ZZ",
             "position":"DF",
             "image":"el-barrio-pau-zz.png"
          },
          {
             "id":7,
             "name":"Olae",
             "position":"DC",
             "image":"el-barrio-olae.png"
          },
          {
             "id":8,
             "name":"O. Boada",
             "position":"DC",
             "image":"el-barrio-o-boada.png"
          },
          {
             "id":9,
             "name":"Baranera",
             "position":"MC",
             "image":"el-barrio-baranera.png"
          },
          {
             "id":10,
             "name":"Capilla",
             "position":"MC",
             "image":"el-barrio-capilla.png"
          }
       ]
    },
    {
       "teamId":2,       
       "players":[
          {
             "id":0,
             "name":"Juanma Glez.",
             "position":"MC",
             "image":"ultimate-mostoles-juanma-glez.png"
          },
          {
             "id":1,
             "name":"Arché",
             "position":"MC",
             "image":"ultimate-mostoles-arch.png"
          },
          {
             "id":2,
             "name":"Iu",
             "position":"POR",
             "image":"ultimate-mostoles-iu.png"
          },
          {
             "id":3,
             "name":"Guti",
             "position":"DF",
             "image":"ultimate-mostoles-guti.png"
          },
          {
             "id":4,
             "name":"Aleix",
             "position":"MC",
             "image":"ultimate-mostoles-aleix.png"
          },
          {
             "id":5,
             "name":"Llur",
             "position":"DC",
             "image":"ultimate-mostoles-llur.png"
          },
          {
             "id":6,
             "name":"Iker",
             "position":"DF",
             "image":"ultimate-mostoles-iker.png"
          },
          {
             "id":7,
             "name":"Ian",
             "position":"DF",
             "image":"ultimate-mostoles-ian.png"
          },
          {
             "id":8,
             "name":"Zea",
             "position":"DC",
             "image":"ultimate-mostoles-zea.png"
          },
          {
             "id":9,
             "name":"Nacho",
             "position":"POR",
             "image":"ultimate-mostoles-nacho.png"
          },
          {
             "id":10,
             "name":"Lucca",
             "position":"MC",
             "image":"ultimate-mostoles-lucca.png"
          }
       ]
    },
    {
       "teamId":3,       
       "players":[
          {
             "id":0,
             "name":"Fran A.",
             "position":"DC",
             "image":"los-troncos-fc-fran-a.png"
          },
          {
             "id":1,
             "name":"Álvaro, E.",
             "position":"DC",
             "image":"los-troncos-fc-lvaro-e..png"
          },
          {
             "id":2,
             "name":"Lechuga, P.",
             "position":"POR",
             "image":"los-troncos-fc-lechuga-p..png"
          },
          {
             "id":3,
             "name":"Soriano, D.",
             "position":"DF",
             "image":"los-troncos-fc-soriano-d..png"
          },
          {
             "id":4,
             "name":"Sánchez, S.",
             "position":"MC",
             "image":"los-troncos-fc-snchez-s..png"
          },
          {
             "id":5,
             "name":"Noel L.",
             "position":"MC",
             "image":"los-troncos-fc-noel-l.png"
          },
          {
             "id":6,
             "name":"Molas, X.",
             "position":"MC",
             "image":"los-troncos-fc-molas-x..png"
          },
          {
             "id":7,
             "name":"Martínez, R.",
             "position":"DC",
             "image":"los-troncos-fc-martnez-r..png"
          },
          {
             "id":8,
             "name":"Dorkis P.",
             "position":"DC",
             "image":"los-troncos-fc-dorkis-p.png"
          },
          {
             "id":9,
             "name":"Nuevo, I.",
             "position":"MC",
             "image":"los-troncos-fc-nuevo-i..png"
          },
          {
             "id":10,
             "name":"Arus, M.",
             "position":"POR",
             "image":"los-troncos-fc-arus-m..png"
          }
       ]
    },
    {
       "teamId":4,       
       "players":[
          {
             "id":0,
             "name":"Pol Alme",
             "position":"MC",
             "image":"saiyans-fc-pol-alme.png"
          },
          {
             "id":1,
             "name":"Briones",
             "position":"POR",
             "image":"saiyans-fc-briones.png"
          },
          {
             "id":2,
             "name":"Gio Ferinu",
             "position":"DC",
             "image":"saiyans-fc-gio-ferinu.png"
          },
          {
             "id":3,
             "name":"Campu",
             "position":"DF",
             "image":"saiyans-fc-campu.png"
          },
          {
             "id":4,
             "name":"Temo",
             "position":"MC",
             "image":"saiyans-fc-temo.png"
          },
          {
             "id":5,
             "name":"C. Valle",
             "position":"MC",
             "image":"saiyans-fc-c-valle.png"
          },
          {
             "id":6,
             "name":"V. Torres",
             "position":"DF",
             "image":"saiyans-fc-v-torres.png"
          },
          {
             "id":7,
             "name":"Feliu",
             "position":"MC",
             "image":"saiyans-fc-feliu.png"
          },
          {
             "id":8,
             "name":"David Alba",
             "position":"DC",
             "image":"saiyans-fc-david-alba.png"
          },
          {
             "id":9,
             "name":"R. Carbó",
             "position":"MC",
             "image":"saiyans-fc-r-carbo.png"
          },
          {
             "id":10,
             "name":"Fajardo",
             "position":"POR",
             "image":"saiyans-fc-fajardo.png"
          }
       ]
    },
    {
       "teamId":5,       
       "players":[
          {
             "id":0,
             "name":"Coro",
             "position":"MC",
             "image":"kunisports-coro.png"
          },
          {
             "id":1,
             "name":"Torrentbó",
             "position":"DC",
             "image":"kunisports-torrentb.png"
          },
          {
             "id":2,
             "name":"Víctor",
             "position":"POR",
             "image":"kunisports-vctor.png"
          },
          {
             "id":3,
             "name":"Guerrero",
             "position":"DF",
             "image":"kunisports-guerrero.png"
          },
          {
             "id":4,
             "name":"Joan Inés",
             "position":"MC",
             "image":"kunisports-joan-ins.png"
          },
          {
             "id":5,
             "name":"Rode",
             "position":"POR",
             "image":"kunisports-rode.png"
          },
          {
             "id":6,
             "name":"Ruggeri",
             "position":"DF",
             "image":"kunisports-ruggeri.png"
          },
          {
             "id":7,
             "name":"Nacho J.",
             "position":"DF",
             "image":"kunisports-nacho-j.png"
          },
          {
             "id":8,
             "name":"Hidalgo",
             "position":"DC",
             "image":"kunisports-hidalgo.png"
          },
          {
             "id":9,
             "name":"Lluc",
             "position":"DC",
             "image":"kunisports-lluc.png"
          },
          {
             "id":10,
             "name":"Miki",
             "position":"DF",
             "image":"kunisports-miki.png"
          }
       ]
    },
    {
       "teamId":6,       
       "players":[
          {
             "id":0,
             "name":"Soriano",
             "position":"DC",
             "image":"jijantes-fc-soriano.png"
          },
          {
             "id":1,
             "name":"Alsina",
             "position":"MC",
             "image":"jijantes-fc-alsina.png"
          },
          {
             "id":2,
             "name":"Pol",
             "position":"POR",
             "image":"jijantes-fc-pol.png"
          },
          {
             "id":3,
             "name":"Jay",
             "position":"DF",
             "image":"jijantes-fc-jay.png"
          },
          {
             "id":4,
             "name":"Quero",
             "position":"MC",
             "image":"jijantes-fc-quero.png"
          },
          {
             "id":5,
             "name":"Arnau M.V",
             "position":"DF",
             "image":"jijantes-fc-arnau-mv.png"
          },
          {
             "id":6,
             "name":"Iván",
             "position":"DC",
             "image":"jijantes-fc-ivn.png"
          },
          {
             "id":7,
             "name":"Maca",
             "position":"MC",
             "image":"jijantes-fc-maca.png"
          },
          {
             "id":8,
             "name":"Noel",
             "position":"DF",
             "image":"jijantes-fc-noel.png"
          },
          {
             "id":9,
             "name":"Dorado",
             "position":"DC",
             "image":"jijantes-fc-dorado.png"
          },
          {
             "id":10,
             "name":"Mario",
             "position":"POR",
             "image":"jijantes-fc-mario.png"
          }
       ]
    },
    {
       "teamId":7,       
       "players":[
          {
             "id":0,
             "name":"Espinosa",
             "position":"MC",
             "image":"porcinos-fc-espinosa.png"
          },
          {
             "id":1,
             "name":"J. Segovia",
             "position":"POR",
             "image":"porcinos-fc-j-segovia.png"
          },
          {
             "id":2,
             "name":"G. Cichero",
             "position":"DF",
             "image":"porcinos-fc-g-cichero.png"
          },
          {
             "id":3,
             "name":"David L.L.",
             "position":"DF",
             "image":"porcinos-fc-david-ll..png"
          },
          {
             "id":4,
             "name":"Toti",
             "position":"MC",
             "image":"porcinos-fc-toti.png"
          },
          {
             "id":5,
             "name":"Carlitos G.",
             "position":"MC",
             "image":"porcinos-fc-carlitos-g.png"
          },
          {
             "id":6,
             "name":"Killian",
             "position":"DC",
             "image":"porcinos-fc-killian.png"
          },
          {
             "id":7,
             "name":"J. Blanco",
             "position":"DC",
             "image":"porcinos-fc-j-blanco.png"
          },
          {
             "id":8,
             "name":"Uri Pons",
             "position":"DC",
             "image":"porcinos-fc-uri-pons.png"
          },
          {
             "id":9,
             "name":"Lao",
             "position":"MC",
             "image":"porcinos-fc-lao.png"
          },
          {
             "id":10,
             "name":"Sergi",
             "position":"POR",
             "image":"porcinos-fc-sergi.png"
          }
       ]
    },
    {
       "teamId":8,       
       "players":[
          {
             "id":0,
             "name":"Poloteli",
             "position":"DF",
             "image":"rayo-barcelona-poloteli.png"
          },
          {
             "id":1,
             "name":"Pelaz",
             "position":"MC",
             "image":"rayo-barcelona-pelaz.png"
          },
          {
             "id":2,
             "name":"Canet",
             "position":"POR",
             "image":"rayo-barcelona-canet.png"
          },
          {
             "id":3,
             "name":"Guillem ZZ",
             "position":"DC",
             "image":"rayo-barcelona-guillem-zz.png"
          },
          {
             "id":4,
             "name":"M. Reyes",
             "position":"DF",
             "image":"rayo-barcelona-m-reyes.png"
          },
          {
             "id":5,
             "name":"Franky P.",
             "position":"MC",
             "image":"rayo-barcelona-franky-p.png"
          },
          {
             "id":6,
             "name":"Dani P.",
             "position":"MC",
             "image":"rayo-barcelona-dani-p.png"
          },
          {
             "id":7,
             "name":"Alejandro",
             "position":"DF",
             "image":"rayo-barcelona-alejandro.png"
          },
          {
             "id":8,
             "name":"Biboum M.",
             "position":"DC",
             "image":"rayo-barcelona-biboum-m.png"
          },
          {
             "id":9,
             "name":"Jonathan",
             "position":"MC",
             "image":"rayo-barcelona-jonathan.png"
          },
          {
             "id":10,
             "name":"Alex Race",
             "position":"DC",
             "image":"rayo-barcelona-alex-race.png"
          }
       ]
    },
    {
       "teamId":9,       
       "players":[
          {
             "id":0,
             "name":"C. Castro",
             "position":"DC",
             "image":"xbuyer-team-c-castro.png"
          },
          {
             "id":1,
             "name":"Capi",
             "position":"POR",
             "image":"xbuyer-team-capi.png"
          },
          {
             "id":2,
             "name":"Poch",
             "position":"DC",
             "image":"xbuyer-team-poch.png"
          },
          {
             "id":3,
             "name":"Iñaki",
             "position":"MC",
             "image":"xbuyer-team-iaki.png"
          },
          {
             "id":4,
             "name":"Dani",
             "position":"DF",
             "image":"xbuyer-team-dani.png"
          },
          {
             "id":5,
             "name":"Granero",
             "position":"DC",
             "image":"xbuyer-team-granero.png"
          },
          {
             "id":6,
             "name":"Goran",
             "position":"MC",
             "image":"xbuyer-team-goran.png"
          },
          {
             "id":7,
             "name":"Bañuls",
             "position":"DF",
             "image":"xbuyer-team-bauls.png"
          },
          {
             "id":8,
             "name":"Franc",
             "position":"MC",
             "image":"xbuyer-team-franc.png"
          },
          {
             "id":9,
             "name":"B. Sierra",
             "position":"DC",
             "image":"xbuyer-team-b-sierra.png"
          },
          {
             "id":10,
             "name":"Sep",
             "position":"POR",
             "image":"xbuyer-team-sep.png"
          }
       ]
    },
    {
       "teamId":10,       
       "players":[
          {
             "id":0,
             "name":"F. Hernandéz",
             "position":"MC",
             "image":"aniquiladores-fc-f-hernandez.png"
          },
          {
             "id":1,
             "name":"Daniel P.",
             "position":"POR",
             "image":"aniquiladores-fc-daniel-p.png"
          },
          {
             "id":2,
             "name":"Galvany",
             "position":"MC",
             "image":"aniquiladores-fc-galvany.png"
          },
          {
             "id":3,
             "name":"Andrés",
             "position":"DF",
             "image":"aniquiladores-fc-andrs.png"
          },
          {
             "id":4,
             "name":"Bernat",
             "position":"MC",
             "image":"aniquiladores-fc-bernat.png"
          },
          {
             "id":5,
             "name":"Paul Mañé",
             "position":"DC",
             "image":"aniquiladores-fc-paul-mae.png"
          },
          {
             "id":6,
             "name":"Jorquera",
             "position":"DF",
             "image":"aniquiladores-fc-jorquera.png"
          },
          {
             "id":7,
             "name":"Gilles V.",
             "position":"MC",
             "image":"aniquiladores-fc-gilles-v.png"
          },
          {
             "id":8,
             "name":"Jadir",
             "position":"DF",
             "image":"aniquiladores-fc-jadir.png"
          },
          {
             "id":9,
             "name":"Roger",
             "position":"MC",
             "image":"aniquiladores-fc-roger.png"
          },
          {
             "id":10,
             "name":"X.Morales",
             "position":"POR",
             "image":"aniquiladores-fc-xmorales.png"
          }
       ]
    },
    {
       "teamId":11,       
       "players":[
          {
             "id":0,
             "name":"Lopo",
             "position":"DF",
             "image":"pio-fc-lopo.png"
          },
          {
             "id":1,
             "name":"Jorge",
             "position":"POR",
             "image":"pio-fc-jorge.png"
          },
          {
             "id":2,
             "name":"Carlitos",
             "position":"DF",
             "image":"pio-fc-carlitos.png"
          },
          {
             "id":3,
             "name":"Pau Fer",
             "position":"MC",
             "image":"pio-fc-pau-fer.png"
          },
          {
             "id":4,
             "name":"I. Cabello",
             "position":"DC",
             "image":"pio-fc-i-cabello.png"
          },
          {
             "id":5,
             "name":"B. Juárez",
             "position":"MC",
             "image":"pio-fc-b-juarez.png"
          },
          {
             "id":6,
             "name":"Turner",
             "position":"DF",
             "image":"pio-fc-turner.png"
          },
          {
             "id":7,
             "name":"Adri",
             "position":"DC",
             "image":"pio-fc-adri.png"
          },
          {
             "id":8,
             "name":"Cokita",
             "position":"MC",
             "image":"pio-fc-cokita.png"
          },
          {
             "id":9,
             "name":"A. Ropero",
             "position":"MC",
             "image":"pio-fc-a-ropero.png"
          },
          {
             "id":10,
             "name":"Santiago",
             "position":"DF",
             "image":"pio-fc-santiago.png"
          }
       ]
    }
 ];